import anthropic
import json
from dotenv import load_dotenv

load_dotenv()

client = anthropic.Anthropic()

ORCHESTRATOR_SYSTEM_PROMPT = """
You are the Orchestrator Agent for TrustLayer by blondebytesecurity.

TrustLayer is an AI content intelligence system with two analysis modes:

MODE 1: AUTHENTICITY
Determines whether content was written by a human or generated by AI.

MODE 2: CREDIBILITY
Determines whether content is credible — are claims supported,
sources cited, language appropriately confident, internally consistent.

MODE 3: BOTH
Runs full authenticity and credibility analysis.

Your role:
- Receive the text and selected mode
- Prepare structured context for downstream agents
- Extract surface observations to inform specialist agents
- Coordinate the analysis chain

Always respond in clean JSON only. No preamble. No markdown.

Format:
{
  "mode": "authenticity/credibility/both",
  "input_summary": "...",
  "domain": "...",
  "complexity": "low/medium/high",
  "approximate_word_count": 0,
  "contains_urls": true/false,
  "contains_citations": true/false,
  "surface_observations": "...",
  "ready_for_analysis": true
}
"""

def orchestrate(text_input: str, mode: str) -> dict:
    """
    Receives raw text input and selected mode.
    Prepares structured context for sub-agents.
    """
    print(f"\n[TrustLayer] Mode selected: {mode.upper()}")
    print("[Orchestrator] Preparing analysis context...\n")

    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=1000,
        system=ORCHESTRATOR_SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": f"""
Mode: {mode}

Analyze and prepare the following text for TrustLayer analysis:

{text_input}
                """
            }
        ]
    )

    raw = response.content[0].text

    try:
        context = json.loads(raw)
        print(f"[Orchestrator] Domain detected: {context.get('domain', 'N/A')}")
        print(f"[Orchestrator] Complexity: {context.get('complexity', 'N/A')}")
        print(f"[Orchestrator] Contains URLs: {context.get('contains_urls', 'N/A')}")
        print(f"[Orchestrator] Ready for analysis\n")
        return {"original_text": text_input, "mode": mode, "context": context}
    except json.JSONDecodeError:
        print("[Orchestrator] Warning: Could not parse JSON, returning raw.")
        return {"original_text": text_input, "mode": mode, "context": raw}