import anthropic
import json
import logging
import os
from datetime import datetime
from agents.pdf_export import export_pdf
from dotenv import load_dotenv

load_dotenv()

# ============================================================
# LOGGING
# ============================================================
logging.basicConfig(
    filename="trustlayer_audit.log",
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)

def audit_log(event: str, detail: str = ""):
    logging.info(f"{event} | {detail}")

# ============================================================
# CONFIG
# ============================================================

REPORTS_DIR = "reports"  # all reports go here, not root dir
MAX_TEXT_IN_REPORT = 500  # chars of original text shown in report — privacy control

# ============================================================
# CLAUDE PROMPT
# ============================================================

SYNTHESIZER_SYSTEM_PROMPT = """
You are the Report Synthesizer Agent for TrustLayer by blondebytesecurity.

TrustLayer is an AI content intelligence system that analyzes content
across two dimensions: Authenticity and Credibility.

You receive findings from all upstream agents and synthesize them
into a clean, professional, branded report.

The report must be useful to both technical and non-technical readers.
Write as if presenting findings to a business owner who needs to
make a decision based on this content.

IMPORTANT: Do NOT reproduce large portions of the original analyzed text
in your report. Reference it only briefly if needed for context.

Structure your report exactly as follows in markdown:

---

# 🔐 TrustLayer Content Intelligence Report
**by blondebytesecurity**
*{datetime}*

---

## Executive Summary
2-3 sentences. Plain English. What did we find and what does it mean?
Written for a non-technical reader who needs to act on this information.

---

## Mode: {AUTHENTICITY / CREDIBILITY / FULL ANALYSIS}

---

{IF AUTHENTICITY OR FULL ANALYSIS:}
## Authenticity Analysis

**Verdict: [STRONG LLM / LIKELY LLM / AMBIGUOUS / LIKELY HUMAN / STRONG HUMAN]**
**Confidence: [LOW / MEDIUM / HIGH]**

### Authenticity Scores
| Dimension | Score | Signal |
|-----------|-------|--------|
| Sentence Structure | X/10 | 🤖 / ⚠️ / ✅ |
| Vocabulary Patterns | X/10 | 🤖 / ⚠️ / ✅ |
| Transition Patterns | X/10 | 🤖 / ⚠️ / ✅ |
| Structural Patterns | X/10 | 🤖 / ⚠️ / ✅ |
| Voice Consistency | X/10 | 🤖 / ⚠️ / ✅ |
| Information Density | X/10 | 🤖 / ⚠️ / ✅ |
| Curiosity Signals | X/10 | 🤖 / ⚠️ / ✅ |
| Opinion Integrity | X/10 | 🤖 / ⚠️ / ✅ |
| Reference Behavior | X/10 | 🤖 / ⚠️ / ✅ |
| Cognitive Fingerprint | X/10 | 🤖 / ⚠️ / ✅ |

**Authenticity Score: X/10**

### Key Authenticity Findings
- Finding one
- Finding two
- Finding three

---

{IF CREDIBILITY OR FULL ANALYSIS:}
## Credibility Analysis

**Overall Credibility: [HIGH / MEDIUM / LOW / CRITICAL RISK]**
**Manipulation Risk: [LOW / MEDIUM / HIGH]**

### Credibility Scores
| Dimension | Score | Signal |
|-----------|-------|--------|
| Citation Coverage | X/10 | ⚠️ / ✅ / ❌ |
| Source Relevance | X/10 | ⚠️ / ✅ / ❌ |
| Internal Consistency | X/10 | ⚠️ / ✅ / ❌ |
| Confidence Calibration | X/10 | ⚠️ / ✅ / ❌ |

**Credibility Score: X/10**

### Citation Breakdown
| Claim | Source | Verdict |
|-------|--------|---------|
| claim | source | ✅ Verified / ⚠️ Misleading / ❌ Contradictory / ❓ Unverifiable |

### High Risk Findings
- Risk one
- Risk two
- Risk three

### Flagged Phrases
Phrases identified as overclaiming or potentially manipulative:
- "phrase one"
- "phrase two"

---

## Recommendations
Specific, actionable recommendations based on findings.
Written for someone deciding whether to trust or publish this content.
- Recommendation one
- Recommendation two
- Recommendation three

---

## TrustLayer Disclaimer
*TrustLayer assesses credibility signals — not ground truth.
A high score means content follows credible practices.
It does not guarantee factual accuracy.
For critical decisions, always verify primary sources directly.*

---

*Report generated by TrustLayer — a blondebytesecurity product*
*blondebytesecurity.com*

---

Use exactly this structure.
Fill all sections relevant to the mode selected.
Skip sections not relevant to the mode.
Emoji guide: 🤖 LLM signal | ⚠️ Ambiguous | ✅ Human/Verified | ❌ Risk
Respond with the markdown report only. No preamble. No JSON.
"""

# ============================================================
# REPORT SAVING
# ============================================================

def save_report(report: str, timestamp: str) -> str:
    """
    Saves report to reports/ directory.
    Returns filepath or error message.
    """
    try:
        os.makedirs(REPORTS_DIR, exist_ok=True)
        filename = f"trustlayer_report_{timestamp}.md"
        filepath = os.path.join(REPORTS_DIR, filename)

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report)

        audit_log("REPORT_SAVED", f"filepath={filepath}")
        return filepath

    except OSError as e:
        audit_log("REPORT_SAVE_FAILED", f"error={str(e)}")
        print(f"[Synthesizer] ⚠️  Could not save report: {str(e)}")
        return None


# ============================================================
# MAIN AGENT FUNCTION
# ============================================================

client = anthropic.Anthropic()

def synthesize_report(confidence_output: dict) -> str:
    """
    Receives fully enriched output from all agents.
    Synthesizes findings into a branded TrustLayer report.
    Handles authenticity, credibility, or both modes.
    Returns the final report as a string.
    """
    print("[Synthesizer] Generating TrustLayer report...\n")

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    mode = confidence_output.get("mode", "both")
    original_text = confidence_output.get("original_text", "")
    context = confidence_output.get("context")
    injection_flagged = confidence_output.get("injection_flagged", False)

    # Privacy control — only pass a snippet of original text to synthesizer
    # Full text already analyzed upstream — synthesizer only needs context
    text_snippet = original_text[:MAX_TEXT_IN_REPORT] + ("..." if len(original_text) > MAX_TEXT_IN_REPORT else "")

    # Authenticity findings
    linguistic_findings = confidence_output.get("linguistic_findings")
    behavioral_findings = confidence_output.get("behavioral_findings")

    # Credibility findings
    citation_findings = confidence_output.get("citation_findings")
    fetch_findings = confidence_output.get("fetch_findings")
    relevance_findings = confidence_output.get("relevance_findings")
    consistency_findings = confidence_output.get("consistency_findings")
    confidence_findings = confidence_output.get("confidence_findings")

    # Calculate scores safely
    ling_score = 0
    beh_score = 0
    rel_score = 0
    con_score = 0
    conf_score = 0

    if isinstance(linguistic_findings, dict):
        ling_score = linguistic_findings.get("linguistic_overall_score", 0)
    if isinstance(behavioral_findings, dict):
        beh_score = behavioral_findings.get("behavioral_overall_score", 0)
    if isinstance(relevance_findings, dict):
        rel_score = relevance_findings.get("relevance_overall_score", 0)
    if isinstance(consistency_findings, dict):
        con_score = consistency_findings.get("consistency_overall_score", 0)
    if isinstance(confidence_findings, dict):
        conf_score = confidence_findings.get("confidence_overall_score", 0)

    auth_score = round((ling_score + beh_score) / 2, 1) if (ling_score and beh_score) else "N/A"
    cred_score = round((rel_score + con_score + conf_score) / 3, 1) if (rel_score and con_score and conf_score) else "N/A"

    audit_log("SYNTHESIZER_START", f"mode={mode} auth_score={auth_score} cred_score={cred_score} injection_flagged={injection_flagged}")

    # Add injection warning to report if flagged
    injection_warning = ""
    if injection_flagged:
        injection_warning = "\n\n⚠️ NOTE: This content contained patterns consistent with prompt injection attempts. Analysis proceeded on content only."

    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=4000,  # increased to avoid silent truncation
        system=SYNTHESIZER_SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": f"""
DateTime: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Mode: {mode.upper()}
Injection Flagged: {injection_flagged}

Original Text Snippet (first {MAX_TEXT_IN_REPORT} chars only):
{text_snippet}

Orchestrator Context:
{json.dumps(context, indent=2)}

--- AUTHENTICITY FINDINGS ---

Linguistic Findings:
{json.dumps(linguistic_findings, indent=2)}

Behavioral Findings:
{json.dumps(behavioral_findings, indent=2)}

Authenticity Score: {auth_score}/10

--- CREDIBILITY FINDINGS ---

Citation Findings:
{json.dumps(citation_findings, indent=2)}

Web Fetch Findings:
{json.dumps(fetch_findings, indent=2)}

Relevance Findings:
{json.dumps(relevance_findings, indent=2)}

Consistency Findings:
{json.dumps(consistency_findings, indent=2)}

Confidence Language Findings:
{json.dumps(confidence_findings, indent=2)}

Credibility Score: {cred_score}/10
{injection_warning}

Generate the full TrustLayer report now.
                """
            }
        ]
    )

    report = response.content[0].text

    # Check for potential truncation
    if response.stop_reason == "max_tokens":
        audit_log("REPORT_TRUNCATED", f"hit max_tokens limit at 4000")
        print("[Synthesizer] ⚠️  Report may be truncated — hit token limit.")
        report += "\n\n*⚠️ Note: Report may be incomplete due to length.*"

    # Save report
    filepath = save_report(report, timestamp)
    if filepath:
        print(f"[Synthesizer] Report saved: {filepath}\n")
        # Auto-generate PDF
        export_pdf(report, filepath)
    
    print(f"[Synthesizer] Report complete.")
    print("=" * 60)
    print(report)
    print("=" * 60)

    audit_log("SYNTHESIZER_COMPLETE", f"timestamp={timestamp} filepath={filepath or 'SAVE_FAILED'}")

    return report